using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

/// <summary>
/// Builds the static isometric clay diorama: a roofless 2x2 building with four
/// rooms (VR bedroom / robot assembly / science lab / storage warehouse).
/// Architecture is procedural primitives; hero assets are Blender FBX files
/// under Assets/Models (generated by BlenderPipeline/gen_*.py).
///
/// Layout (top view, camera sits SW looking NE):
///   NW = Bedroom     NE = Assembly
///   SW = Lab         SE = Storage
/// </summary>
public static class IsometricWorldBuilder
{
    const string ScenePath = "Assets/Scenes/IsometricWorld.unity";

    const float WallH = 3.0f;      // exterior/interior wall height
    const float ExtT = 0.35f;      // exterior wall thickness
    const float IntT = 0.30f;      // interior wall thickness
    const float Half = 12f;        // building outer half-extent
    const float CurbH = 0.28f;     // low curb on the open (S/W) sides
    const float DoorW = 1.8f, DoorH = 2.2f;

    static Material clay, clayFloor;
    static System.Random rng;

    // ------------------------------------------------------------ menu items

    [MenuItem("Tools/Isometric World/Build World")]
    public static void BuildWorld()
    {
        AssetDatabase.Refresh();
        rng = new System.Random(42);

        clay = EnsureMat("Assets/Materials/ClayMatte.mat", Hex("#E8EAF0"));
        clayFloor = EnsureMat("Assets/Materials/ClayFloor.mat", Hex("#DCE0EA"));
        EnsureSSAO("Assets/Settings/PC_Renderer.asset");
        EnsureSSAO("Assets/Settings/Mobile_Renderer.asset");
        ExtendShadowDistance("Assets/Settings/PC_RPAsset.asset");
        ExtendShadowDistance("Assets/Settings/Mobile_RPAsset.asset");

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var root = new GameObject("IsometricWorld").transform;
        BuildArchitecture(Group("Architecture", root));
        BuildBedroom(Group("Bedroom", root));
        BuildLab(Group("Lab", root));
        BuildAssembly(Group("Assembly", root));
        BuildStorage(Group("Storage", root));
        BuildLightingAndCamera();

        Directory.CreateDirectory(Path.Combine(Application.dataPath, "Scenes"));
        EditorSceneManager.SaveScene(scene, ScenePath);
        AssetDatabase.SaveAssets();
        Debug.Log("[IsometricWorldBuilder] World built and saved to " + ScenePath);
    }

    [MenuItem("Tools/Isometric World/Render Screenshot")]
    public static void RenderScreenshot()
    {
        var cam = Camera.main;
        if (cam == null) cam = Object.FindFirstObjectByType<Camera>();
        if (cam == null) { Debug.LogError("No camera in scene - build the world first."); return; }

        const int w = 1920, h = 1080;
        var rt = new RenderTexture(w, h, 24, RenderTextureFormat.ARGB32);
        var prevTarget = cam.targetTexture;

        var request = new RenderPipeline.StandardRequest();
        if (RenderPipeline.SupportsRenderRequest(cam, request))
        {
            request.destination = rt;
            RenderPipeline.SubmitRenderRequest(cam, request);
        }
        else
        {
            cam.targetTexture = rt;
            cam.Render();
        }

        var prevActive = RenderTexture.active;
        RenderTexture.active = rt;
        var tex = new Texture2D(w, h, TextureFormat.RGB24, false);
        tex.ReadPixels(new Rect(0, 0, w, h), 0, 0);
        tex.Apply();
        RenderTexture.active = prevActive;
        cam.targetTexture = prevTarget;

        string dir = Path.Combine(Directory.GetParent(Application.dataPath).FullName, "Screenshots");
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, "iso_world.png");
        File.WriteAllBytes(path, tex.EncodeToPNG());
        Object.DestroyImmediate(tex);
        rt.Release();
        Object.DestroyImmediate(rt);
        Debug.Log("[IsometricWorldBuilder] Screenshot saved to " + path);
    }

    /// <summary>Batch-mode entry: -executeMethod IsometricWorldBuilder.BuildAndScreenshotBatch</summary>
    public static void BuildAndScreenshotBatch()
    {
        BuildWorld();
        RenderScreenshot();
    }

    /// <summary>Diagnostic: open the saved scene and render a plain top-down plan view.</summary>
    public static void RenderTopDownBatch()
    {
        EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
        var camGo = new GameObject("TopCam");
        var cam = camGo.AddComponent<Camera>();
        cam.orthographic = true;
        cam.orthographicSize = 13.5f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = Hex("#E7EBF2");
        cam.transform.position = new Vector3(0, 60, 0);
        cam.transform.rotation = Quaternion.Euler(90, 0, 0);

        const int w = 1400, h = 1400;
        var rt = new RenderTexture(w, h, 24);
        cam.targetTexture = rt;
        cam.Render();
        RenderTexture.active = rt;
        var tex = new Texture2D(w, h, TextureFormat.RGB24, false);
        tex.ReadPixels(new Rect(0, 0, w, h), 0, 0);
        tex.Apply();
        string dir = Path.Combine(Directory.GetParent(Application.dataPath).FullName, "Screenshots");
        Directory.CreateDirectory(dir);
        File.WriteAllBytes(Path.Combine(dir, "iso_topdown.png"), tex.EncodeToPNG());
        Debug.Log("[IsometricWorldBuilder] Top-down saved.");
    }

    // ---------------------------------------------------------- architecture

    struct Opening { public float center, width, bottom, top;
        public Opening(float c, float w, float b, float t) { center = c; width = w; bottom = b; top = t; } }

    static void BuildArchitecture(Transform parent)
    {
        // floor slab with apron extending past the walls
        Box(parent, "FloorSlab", new Vector3(0, -0.2f, 0), new Vector3(Half * 2 + 1.8f, 0.4f, Half * 2 + 1.8f), clayFloor);

        var win = new Opening(-6.2f, 2.4f, 0.95f, 2.5f);   // bedroom window (N wall)
        var doorNS1 = new Opening(6f, DoorW, 0, DoorH);     // x=0 wall: bedroom <-> assembly
        var doorNS2 = new Opening(-6f, DoorW, 0, DoorH);    // x=0 wall: lab <-> storage
        var doorEW1 = new Opening(-6f, DoorW, 0, DoorH);    // z=0 wall: bedroom <-> lab
        var doorEW2 = new Opening(9.7f, DoorW, 0, DoorH);   // z=0 wall: assembly <-> storage

        // exterior: N + E full height, S + W low curbs (open toward camera)
        StraightWall(parent, "Wall_N", true, Half - ExtT / 2, -Half, Half, WallH, ExtT, new[] { win });
        StraightWall(parent, "Wall_E", false, Half - ExtT / 2, -Half, Half - ExtT, WallH, ExtT, null);
        StraightWall(parent, "Curb_S", true, -Half + ExtT / 2, -Half, Half, CurbH, ExtT, null);
        StraightWall(parent, "Curb_W", false, -Half + ExtT / 2, -Half + ExtT, Half - ExtT, CurbH, ExtT, null);

        // interior cross walls
        float inner = Half - ExtT;
        StraightWall(parent, "Wall_Mid_NS", false, 0, -inner, inner, WallH, IntT, new[] { doorNS1, doorNS2 });
        StraightWall(parent, "Wall_Mid_EW", true, 0, -inner, inner, WallH, IntT, new[] { doorEW1, doorEW2 });

        // open door leafs at two doorways
        DoorLeaf(parent, new Vector3(-IntT / 2f, 0, 6f - DoorW / 2f), 70f);    // bedroom<->assembly
        DoorLeaf(parent, new Vector3(-6f - DoorW / 2f, 0, IntT / 2f), -65f, true); // bedroom<->lab
    }

    /// <summary>Axis-aligned wall with rectangular openings (doors/windows).</summary>
    static void StraightWall(Transform parent, string name, bool alongX, float fixedCoord,
                             float from, float to, float height, float thick, Opening[] openings)
    {
        var wall = Group(name, parent);
        var opens = (openings ?? new Opening[0]).OrderBy(o => o.center).ToList();

        float cursor = from;
        foreach (var o in opens)
        {
            float a = o.center - o.width / 2, b = o.center + o.width / 2;
            if (a > cursor) Seg(wall, alongX, fixedCoord, cursor, a, 0, height, thick);
            if (o.bottom > 0.01f) Seg(wall, alongX, fixedCoord, a, b, 0, o.bottom, thick);       // sill
            if (o.top < height - 0.01f) Seg(wall, alongX, fixedCoord, a, b, o.top, height, thick); // header
            cursor = b;
        }
        if (cursor < to) Seg(wall, alongX, fixedCoord, cursor, to, 0, height, thick);
    }

    static void Seg(Transform parent, bool alongX, float fixedCoord, float from, float to,
                    float y0, float y1, float thick)
    {
        float len = to - from, mid = (from + to) / 2;
        Vector3 center = alongX ? new Vector3(mid, (y0 + y1) / 2, fixedCoord)
                                : new Vector3(fixedCoord, (y0 + y1) / 2, mid);
        Vector3 size = alongX ? new Vector3(len, y1 - y0, thick)
                              : new Vector3(thick, y1 - y0, len);
        Box(parent, "Seg", center, size, clay);
    }

    static void DoorLeaf(Transform parent, Vector3 hinge, float openAngle, bool alongX = false)
    {
        var pivot = new GameObject("DoorLeaf").transform;
        pivot.SetParent(parent, false);
        pivot.position = hinge;
        pivot.rotation = Quaternion.Euler(0, (alongX ? 90f : 0f) + openAngle, 0);
        Box(pivot, "Leaf", new Vector3(0, DoorH / 2 - 0.02f, DoorW / 2 - 0.03f),
            new Vector3(0.06f, DoorH - 0.06f, DoorW - 0.1f), clay);
    }

    // ---------------------------------------------------------------- rooms

    static void BuildBedroom(Transform parent)
    {
        // sleeping corner (N/W)
        Place(parent, "Furniture/bed", new Vector3(-9.55f, 0, 10.5f), 180);
        Scaled(parent, "Furniture/unit_box_beveled", new Vector3(-8.25f, 0, 11.25f), 0,
               new Vector3(0.55f, 0.5f, 0.42f));                                  // nightstand
        Place(parent, "Furniture/floor_lamp", new Vector3(-11.15f, 0, 9.15f), 0);

        // desk / study run along the N wall
        Place(parent, "Furniture/desk", new Vector3(-3.0f, 0, 11.0f), 180);
        Place(parent, "Furniture/monitor_keyboard", new Vector3(-3.0f, 0.76f, 11.05f), 180);
        Place(parent, "Furniture/pc_tower", new Vector3(-1.8f, 0, 11.2f), 180);
        Place(parent, "Furniture/office_chair", new Vector3(-3.1f, 0, 10.05f), 10);
        Place(parent, "Furniture/bookshelf", new Vector3(-6.5f, 0, 11.32f), 180);
        Place(parent, "Furniture/cabinet", new Vector3(-1.05f, 0, 11.2f), 180);   // wardrobe

        // lounge (open W side, low furniture so the camera sees in)
        Place(parent, "Furniture/sofa", new Vector3(-10.75f, 0, 6.5f), 90);
        Place(parent, "Furniture/coffee_table", new Vector3(-9.15f, 0, 6.45f), 0);

        Cylinder(parent, "Rug", new Vector3(-6.1f, 0.02f, 5.4f),
                 new Vector3(4.8f, 0.02f, 3.4f), clay);   // lighter tone than floor

        Place(parent, "Characters/person_vr", new Vector3(-6.1f, 0, 5.2f), 225);
        Plant(parent, new Vector3(-11.15f, 0, 2.6f));
        Plant(parent, new Vector3(-1.5f, 0, 8.2f));
    }

    static void BuildLab(Transform parent)
    {
        Place(parent, "Furniture/gantry_frame", new Vector3(-6f, 0, -5.6f), 0);
        Place(parent, "Robots/robot_humanoid_hanging", new Vector3(-6f, 0, -5.6f), 195);

        Place(parent, "Furniture/lab_bench_equip", new Vector3(-11.0f, 0, -5.2f), 90);
        Place(parent, "Furniture/lab_bench_terminal", new Vector3(-8.6f, 0, -0.62f), 180);
        Place(parent, "Furniture/lab_bench_equip", new Vector3(-3.2f, 0, -0.62f), 180);
        Place(parent, "Machines/control_panel", new Vector3(-4.15f, 0, -7.0f), -40);
        Place(parent, "Furniture/stool", new Vector3(-10.0f, 0, -3.9f), 0);

        Place(parent, "Characters/scientist_pointing", new Vector3(-4.75f, 0, -4.55f), 230);
        Place(parent, "Characters/scientist_armscrossed", new Vector3(-7.55f, 0, -4.35f), 130);
        Place(parent, "Characters/scientist_tablet", new Vector3(-6.1f, 0, -7.95f), 3);

        // tech backdrop along the tall interior walls (N at z=0, E at x=0)
        Place(parent, "Furniture/server_rack", new Vector3(-1.35f, 0, -0.72f), 180);
        Place(parent, "Furniture/cabinet", new Vector3(-0.68f, 0, -3.2f), -90);
        Place(parent, "Furniture/tool_cart", new Vector3(-8.35f, 0, -6.75f), -20);
        Place(parent, "Furniture/whiteboard", new Vector3(-8.9f, 0, -8.35f), 28);
        Place(parent, "Furniture/stool", new Vector3(-4.7f, 0, -3.45f), 0);

        Place(parent, "Furniture/barrel", new Vector3(-11.15f, 0, -9.1f), 0);
        Place(parent, "Furniture/crate", new Vector3(-10.95f, 0, -7.35f), 12);
        Plant(parent, new Vector3(-1.15f, 0, -10.8f));
        Plant(parent, new Vector3(-11.2f, 0, -1.5f));
    }

    static void BuildAssembly(Transform parent)
    {
        Place(parent, "Machines/conveyor_belt", new Vector3(6f, 0, 7.3f), 0);
        Place(parent, "Robots/robot_arm", new Vector3(4.6f, 0, 8.35f), 180);
        Place(parent, "Robots/robot_arm", new Vector3(7.4f, 0, 6.25f), 0);
        Place(parent, "Machines/control_panel", new Vector3(9.7f, 0, 5.9f), -90);

        Place(parent, "Furniture/desk", new Vector3(6.3f, 0, 4.55f), 0);
        Place(parent, "Furniture/monitor_keyboard", new Vector3(5.9f, 0.76f, 4.5f), 0);
        Place(parent, "Furniture/monitor_keyboard", new Vector3(6.8f, 0.76f, 4.58f), 8);
        Place(parent, "Furniture/office_chair", new Vector3(6.3f, 0, 3.75f), 180);
        Place(parent, "Characters/person_sitting", new Vector3(6.3f, 0.03f, 3.72f), 0);
        Place(parent, "Characters/person_standing_a", new Vector3(5.2f, 0, 3.25f), 18);
        Place(parent, "Characters/person_standing_b", new Vector3(7.45f, 0, 3.3f), -14);

        // machine-side infrastructure (tall items on far N + E walls)
        Place(parent, "Furniture/server_rack", new Vector3(3.6f, 0, 11.2f), 180);
        Place(parent, "Furniture/cabinet", new Vector3(11.2f, 0, 9.1f), -90);
        Place(parent, "Furniture/tool_cart", new Vector3(8.75f, 0, 8.15f), -8);
        Place(parent, "Furniture/whiteboard", new Vector3(9.0f, 0, 5.1f), -90);

        // staged material around the cell
        Place(parent, "Furniture/pallet", new Vector3(10.4f, 0, 2.7f), 12);
        BoxStack(parent, new Vector3(10.4f, 0.16f, 2.7f), 12, 2);
        Place(parent, "Furniture/pallet", new Vector3(10.75f, 0, 10.5f), -7);
        BoxStack(parent, new Vector3(10.75f, 0.16f, 10.5f), -7, 3);
        Place(parent, "Furniture/barrel", new Vector3(1.95f, 0, 10.55f), 0);
        Place(parent, "Furniture/barrel", new Vector3(2.62f, 0, 10.35f), 0);
        Place(parent, "Furniture/barrel", new Vector3(2.25f, 0, 9.85f), 0);
        Place(parent, "Furniture/crate", new Vector3(2.4f, 0, 7.7f), 18);
        Place(parent, "Furniture/crate", new Vector3(3.05f, 0, 8.35f), -10);
        Place(parent, "Furniture/crate", new Vector3(2.75f, 0.62f, 8.0f), 6);
        Scaled(parent, "Furniture/unit_box_beveled", new Vector3(2.6f, 0, 6.1f), 20,
               new Vector3(0.6f, 0.55f, 0.6f));
    }

    static void BuildStorage(Transform parent)
    {
        // shelves along the E wall, the N + W interior walls, and centre rows
        var shelfSpots = new List<(Vector3 pos, float rot)>
        {
            (new Vector3(11.3f, 0, -2.6f), 90), (new Vector3(11.3f, 0, -4.85f), 90),
            (new Vector3(11.3f, 0, -7.1f), 90),
            (new Vector3(2.9f, 0, -0.6f), 0), (new Vector3(5.1f, 0, -0.6f), 0),
            (new Vector3(4.6f, 0, -5.9f), 0), (new Vector3(6.7f, 0, -5.9f), 0),
            (new Vector3(0.75f, 0, -3.2f), -90), (new Vector3(0.75f, 0, -5.55f), -90),
        };
        foreach (var (pos, rot) in shelfSpots)
        {
            Place(parent, "Furniture/shelf_unit", pos, rot);
            FillShelf(parent, pos, rot);
        }

        Place(parent, "Furniture/pallet", new Vector3(9.7f, 0, -9.9f), 8);
        BoxStack(parent, new Vector3(9.7f, 0.16f, -9.9f), 8, 3);
        Place(parent, "Furniture/pallet", new Vector3(2.7f, 0, -8.3f), -6);
        Place(parent, "Furniture/barrel", new Vector3(2.5f, 0.16f, -8.45f), 0);
        Place(parent, "Furniture/barrel", new Vector3(3.0f, 0.16f, -8.05f), 0);

        Scaled(parent, "Furniture/unit_box_beveled", new Vector3(2.2f, 0, -4.4f), -8,
               new Vector3(0.68f, 0.6f, 0.68f));
        Scaled(parent, "Furniture/unit_box_beveled", new Vector3(2.28f, 0.6f, -4.32f), 14,
               new Vector3(0.45f, 0.42f, 0.45f));

        // loose crates scattered on the floor
        Place(parent, "Furniture/crate", new Vector3(5.6f, 0, -10.6f), 10);
        Place(parent, "Furniture/crate", new Vector3(6.3f, 0, -10.3f), -14);
        Place(parent, "Furniture/crate", new Vector3(5.95f, 0.62f, -10.45f), 4);
        Place(parent, "Furniture/crate", new Vector3(3.6f, 0, -10.7f), 22);

        // the humanoid robot carries a crate toward the assembly doorway (x=9.7, z=0)
        Place(parent, "Robots/robot_humanoid_carrying", new Vector3(9.0f, 0, -3.4f), 4);
        Plant(parent, new Vector3(11.2f, 0, -11.0f));
    }

    /// <summary>Scatter beveled boxes on the shelf levels of a shelf_unit.</summary>
    static void FillShelf(Transform parent, Vector3 unitPos, float rotY)
    {
        float[] levels = { 0.122f, 0.822f, 1.522f };
        var rot = Quaternion.Euler(0, rotY, 0);
        foreach (float y in levels)
        {
            int n = rng.Next(2, 5);
            for (int i = 0; i < n; i++)
            {
                float s = 0.30f + (float)rng.NextDouble() * 0.22f;
                float x = -0.78f + i * (1.6f / Mathf.Max(n - 1, 1)) + (float)rng.NextDouble() * 0.12f - 0.06f;
                float zj = ((float)rng.NextDouble() - 0.5f) * 0.12f;
                Vector3 local = new Vector3(x, y, zj);
                Scaled(parent, "Furniture/unit_box_beveled", unitPos + rot * local,
                       rotY + rng.Next(-14, 14), new Vector3(s, s * (0.8f + (float)rng.NextDouble() * 0.4f), s));
            }
        }
    }

    static void BoxStack(Transform parent, Vector3 basePos, float rotY, int count)
    {
        float y = basePos.y;
        float s0 = 0.72f;
        for (int i = 0; i < count; i++)
        {
            float s = s0 - i * 0.16f;
            float h = s * 0.9f;
            Scaled(parent, "Furniture/unit_box_beveled",
                   new Vector3(basePos.x + ((float)rng.NextDouble() - 0.5f) * 0.08f, y,
                               basePos.z + ((float)rng.NextDouble() - 0.5f) * 0.08f),
                   rotY + rng.Next(-16, 16), new Vector3(s, h, s));
            y += h;
        }
    }

    static void Plant(Transform parent, Vector3 pos)
    {
        var g = Group("Plant", parent);
        Cylinder(g, "Pot", pos + new Vector3(0, 0.11f, 0), new Vector3(0.30f, 0.11f, 0.30f), clay);
        Cylinder(g, "Trunk", pos + new Vector3(0, 0.35f, 0), new Vector3(0.045f, 0.14f, 0.045f), clay);
        Sphere(g, "Canopy_a", pos + new Vector3(0, 0.66f, 0), 0.42f, clay);
        Sphere(g, "Canopy_b", pos + new Vector3(0.14f, 0.88f, 0.06f), 0.30f, clay);
        Sphere(g, "Canopy_c", pos + new Vector3(-0.13f, 0.84f, -0.08f), 0.26f, clay);
    }

    // ------------------------------------------------------ lighting/camera

    static void BuildLightingAndCamera()
    {
        var lightGo = new GameObject("Directional Light");
        var light = lightGo.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1.25f;
        light.color = Hex("#FFFDF7");
        light.shadows = LightShadows.Soft;
        light.shadowStrength = 0.72f;
        light.transform.rotation = Quaternion.Euler(50, 128, 0);

        RenderSettings.ambientMode = AmbientMode.Flat;
        RenderSettings.ambientLight = Hex("#9AA6BC");   // dimmer so form + AO read
        RenderSettings.fog = false;

        var camGo = new GameObject("Main Camera");
        camGo.tag = "MainCamera";
        var cam = camGo.AddComponent<Camera>();
        cam.orthographic = true;
        cam.orthographicSize = 10.5f;
        cam.nearClipPlane = 0.3f;
        cam.farClipPlane = 200f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = Hex("#E7EBF2");
        camGo.AddComponent<UniversalAdditionalCameraData>().renderPostProcessing = true;

        var rot = Quaternion.Euler(35.264f, 45f, 0);
        camGo.transform.rotation = rot;
        camGo.transform.position = new Vector3(0, 1f, 0) - rot * Vector3.forward * 42f;

        var controller = camGo.AddComponent<IsometricCameraController>();
        controller.defaultDistance = 42f;
        controller.maxOrthographicSize = 22f;
    }

    // ------------------------------------------------------------- plumbing

    static Transform Group(string name, Transform parent)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        return go.transform;
    }

    static GameObject Box(Transform parent, string name, Vector3 center, Vector3 size, Material mat)
    {
        var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
        go.name = name;
        go.transform.SetParent(parent, false);
        go.transform.position = center;
        go.transform.localScale = size;
        go.GetComponent<MeshRenderer>().sharedMaterial = mat;
        return go;
    }

    static GameObject Cylinder(Transform parent, string name, Vector3 center, Vector3 scale, Material mat)
    {
        var go = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        go.name = name;
        go.transform.SetParent(parent, false);
        go.transform.position = center;
        go.transform.localScale = scale;
        go.GetComponent<MeshRenderer>().sharedMaterial = mat;
        return go;
    }

    static GameObject Sphere(Transform parent, string name, Vector3 center, float dia, Material mat)
    {
        var go = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        go.name = name;
        go.transform.SetParent(parent, false);
        go.transform.position = center;
        go.transform.localScale = Vector3.one * dia;
        go.GetComponent<MeshRenderer>().sharedMaterial = mat;
        return go;
    }

    static GameObject Place(Transform parent, string modelPath, Vector3 pos, float rotY)
        => Scaled(parent, modelPath, pos, rotY, Vector3.one);

    // Places a prefab referenced by full asset path (e.g. an AI-generated robot prefab),
    // as opposed to Place/Scaled which resolve an FBX under Assets/Models/.
    static GameObject PlacePrefab(Transform parent, string assetPath, Vector3 pos, float rotY)
    {
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
        if (prefab == null)
        {
            Debug.LogWarning("[IsometricWorldBuilder] Missing prefab: " + assetPath);
            return null;
        }
        var go = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent);
        go.transform.position = pos;
        go.transform.rotation = Quaternion.Euler(0, rotY, 0);
        go.transform.localScale = Vector3.one;
        foreach (var r in go.GetComponentsInChildren<MeshRenderer>())
        {
            var mats = new Material[r.sharedMaterials.Length];
            for (int i = 0; i < mats.Length; i++) mats[i] = clay;
            r.sharedMaterials = mats;
        }
        return go;
    }

    static GameObject Scaled(Transform parent, string modelPath, Vector3 pos, float rotY, Vector3 scale)
    {
        string assetPath = "Assets/Models/" + modelPath + ".fbx";
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
        if (prefab == null)
        {
            Debug.LogWarning("[IsometricWorldBuilder] Missing model: " + assetPath);
            return null;
        }
        var go = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent);
        go.transform.position = pos;
        go.transform.rotation = Quaternion.Euler(0, rotY, 0);
        go.transform.localScale = scale;
        foreach (var r in go.GetComponentsInChildren<MeshRenderer>())
        {
            var mats = new Material[r.sharedMaterials.Length];
            for (int i = 0; i < mats.Length; i++) mats[i] = clay;
            r.sharedMaterials = mats;
        }
        return go;
    }

    static Material EnsureMat(string path, Color color)
    {
        Directory.CreateDirectory(Path.Combine(Application.dataPath, "Materials"));
        var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (mat == null)
        {
            mat = new Material(Shader.Find("Universal Render Pipeline/Lit"));
            AssetDatabase.CreateAsset(mat, path);
        }
        mat.SetColor("_BaseColor", color);
        mat.SetFloat("_Smoothness", 0.05f);
        mat.SetFloat("_Metallic", 0f);
        EditorUtility.SetDirty(mat);
        return mat;
    }

    static Color Hex(string hex)
    {
        ColorUtility.TryParseHtmlString(hex, out var c);
        return c;
    }

    // ------------------------------------------------------------- URP setup

    static void EnsureSSAO(string rendererPath)
    {
        var data = AssetDatabase.LoadAssetAtPath<ScriptableRendererData>(rendererPath);
        if (data == null) { Debug.LogWarning("Renderer data not found: " + rendererPath); return; }

        var feature = data.rendererFeatures
            .FirstOrDefault(f => f != null && f.GetType().Name == "ScreenSpaceAmbientOcclusion");

        if (feature == null)
        {
            var type = typeof(ScriptableRendererData).Assembly
                .GetType("UnityEngine.Rendering.Universal.ScreenSpaceAmbientOcclusion");
            if (type == null) { Debug.LogWarning("SSAO feature type not found in URP assembly."); return; }

            feature = (ScriptableRendererFeature)ScriptableObject.CreateInstance(type);
            feature.name = "ScreenSpaceAmbientOcclusion";
            AssetDatabase.AddObjectToAsset(feature, data);

            var so = new SerializedObject(data);
            var list = so.FindProperty("m_RendererFeatures");
            list.arraySize++;
            list.GetArrayElementAtIndex(list.arraySize - 1).objectReferenceValue = feature;
            var map = so.FindProperty("m_RendererFeatureMap");
            if (map != null)
            {
                map.arraySize++;
                AssetDatabase.TryGetGUIDAndLocalFileIdentifier(feature, out _, out long localId);
                map.GetArrayElementAtIndex(map.arraySize - 1).longValue = localId;
            }
            so.ApplyModifiedProperties();
            Debug.Log("[IsometricWorldBuilder] Added SSAO to " + rendererPath);
        }

        // Always (re)apply strong clay-render AO settings, even if it pre-existed.
        var fso = new SerializedObject(feature);
        SetFloat(fso, "m_Settings.Intensity", 1.7f);
        SetFloat(fso, "m_Settings.Radius", 0.5f);
        SetFloat(fso, "m_Settings.DirectLightingStrength", 0.55f);
        var falloff = fso.FindProperty("m_Settings.Falloff");
        if (falloff != null) falloff.floatValue = 120f;
        fso.ApplyModifiedProperties();
        EditorUtility.SetDirty(feature);
        EditorUtility.SetDirty(data);
        AssetDatabase.SaveAssets();
        Debug.Log("[IsometricWorldBuilder] SSAO settings applied to " + rendererPath);
    }

    static void SetFloat(SerializedObject so, string path, float value)
    {
        var p = so.FindProperty(path);
        if (p != null) p.floatValue = value;
    }

    static void ExtendShadowDistance(string rpAssetPath)
    {
        var rp = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(rpAssetPath);
        if (rp == null) return;
        rp.shadowDistance = Mathf.Max(rp.shadowDistance, 120f);
        EditorUtility.SetDirty(rp);
    }
}
